# Generated by Django 3.1.3 on 2020-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='game',
            name='maker',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
