# Generated by Django 3.1.3 on 2020-11-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_auto_20201128_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
