# Generated by Django 3.1.3 on 2020-11-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0003_remove_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='img1',
            new_name='game_img',
        ),
    ]
