# Generated by Django 3.1.3 on 2020-12-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0003_remove_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='img1',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='category', to='raterapi.category'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(default='', height_field='300', upload_to='', verbose_name='game_image', width_field='300'),
        ),
    ]
