# Generated by Django 3.1.3 on 2020-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0004_auto_20201128_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_img',
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(default='', height_field='300', upload_to='', verbose_name='game_image', width_field='300'),
        ),
    ]
