# Generated by Django 3.1.3 on 2020-12-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0005_auto_20201205_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='raterapi.game'),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='raterapi.player'),
        ),
    ]
